image: docker:20.10.16

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: movie_postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/movie_postgres
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin

stages:
  - test

before_script:
  - apk add --no-cache py3-pip
  - pip install PyYAML

maven-test:
  stage: test
  script:
    - docker-compose up -d
    - mvn clean test
    - docker-compose down