variables:
  DOCKER_DRIVER: overlay2
  POSTGRES_DB: movie_postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5454
  DOCKER_HOST: tcp://docker:2375

stages:
  - docker
  - test

image: maven:3.8.6-openjdk-17  # Použij image s OpenJDK 17

services:
  - name: docker:19.03.12-dind
    alias: docker
    entrypoint: ["dockerd", "--host=tcp://0.0.0.0:2375"]

docker:
  stage: docker
  script:
    - docker-compose up -d

test:
  stage: test
  script:
    - mvn test