stages:
  - backend
  
backend:
  stage: backend
  image: jelastic/maven:3.9.5-openjdk-21
  before_script:
    - chmod +x mvnw
  script:
    - ./mvnw package
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths: 
      - "target"

