stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DB_HOST: localhost
  DB_PORT: 5454

build:
  stage: build
  image: maven:3.8-jdk-17
  script:
    - mvn clean package -DskipTests

test:
  stage: test
  image: maven:3.8.6-jdk-17
  services:
    - docker:20.10.16-dind
  before_script:
    - apt-get update && apt-get install -y docker.io python3-pip netcat 
    - pip3 install docker-compose 
  script:
    - docker-compose up -d  
    - echo "Čekám na inicializaci PostgreSQL (max 60 sekund)..."
    - timeout 60 bash -c 'while ! nc -z $DB_HOST $DB_PORT; do sleep 2; done'  
    - mvn test 