stages:
  - setup
  - test
  - cleanup

services:
  - name: docker:19.03.12
    alias: docker

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "/certs"
  POSTGRES_DB: "movie_test"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"

before_script:
  - apk add --no-cache docker-cli

setup:
  stage: setup
  script:
    - docker-compose -f docker-compose.yml up -d

test:
  stage: test
  script:
    - mvn clean install

cleanup:
  stage: cleanup
  script:
    - docker-compose down
