stages:
  - setup
  - test
  - deploy

variables:
  POSTGRES_DB: movie_postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5454

services:
  - name: docker:19.03.12-dind
    alias: docker

before_script:
  - apk update && apk install curl
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker info 

test:
  stage: test
  script:
    - echo "Waiting for PostgreSQL to start"
    - dockerize -wait tcp://localhost:5432 -timeout 1m 
    - mvn test