variables:
  DOCKER_DRIVER: overlay2
  POSTGRES_DB: movie_postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5454  

stages:
  - docker
  - test

image:
  name: docker/compose:latest

services:
  - docker:19.03.12-dind



docker:
  stage: docker
  
  script:
    - docker-compose up -d




test:
  stage: test
  script:
    - mvn test