version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=admin 
      - POSTGRES_DB=movie_postgres
    ports:
      - '5454:5432'
    volumes:
      - movie_db:/tmp/postgres/data
volumes:
  movie_db:
    driver: local
